# Generated by Django 4.2.7 on 2023-12-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='city',
            field=models.CharField(choices=[('Dushanbe', 'Dushanbe'), ('Kulob', 'Kulob'), ('Kujand', 'Kujand'), ('ВМКБ', 'ВМКБ'), ('Hisor', 'Hisor'), ('Bokhtar', 'Bokhtar')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='delivery',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='get_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='payed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='made_in',
            field=models.IntegerField(choices=[('germany', 'germany'), ('turkey', 'turkey'), ('china', 'china'), ('B/U Dubai', 'B/U Dubai')]),
        ),
    ]
